#!/bin/sh
# https://github.com/docker-library/php/blob/9abc1efe542b56aa93835e4987d5d4a88171b232/5.6/docker-php-entrypoint
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php "$@"
fi

exec "$@"
